image: node:20

cache:
  paths:
    - node_modules/

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
